on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  compile_linux:
    name: Build Linux Executables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Release for linux-x64
        run: dotnet publish --no-restore -r linux-x64 -p:BuildNumber="${{ github.run_number }}" -p:Version="${{ inputs.VERSION }}"

      - name: Upload Release for linux-x64
        uses: actions/upload-artifact@v5
        with:
          name: MelonLoader.Installer.Linux
          path: Output/linux-x64