on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      RELEASE_NAME:
        required: true
        type: string
  
jobs:
  upload_github:
    name: Upload GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: Download Windows x64 Artifact
        uses: actions/download-artifact@v8
        with:
          name: MelonLoader.Installer
          path: ./compiled_release
        
      - name: Download Linux x64 Artifact
        uses: actions/download-artifact@v8
        with:
          name: MelonLoader.Installer.Linux
          path: ./compiled_release
        
      - name: Download MacOS Artifact
        uses: actions/download-artifact@v8
        with:
          name: MelonLoader.Installer.MacOS
          path: ./compiled_release

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          body_path: RELEASE-NOTES.md
          tag: ${{ inputs.TAG }}
          release_name: ${{ inputs.RELEASE_NAME }}
          files: |
            compiled_release/MelonLoader.Installer.exe
            compiled_release/MelonLoader.Installer.Linux
            compiled_release/MelonLoader.Installer.MacOS.dmg
